### ISSUE TITLE
Error installing aeroframe

### ISSUE THREAD

**Issue by IbnFrnas** [airinnova/aeroframe#4]
I open conda lista and it seems to be installed but when I run "aeroframe -h" the following message appears

"aeroframe" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

**Comment by blueangels88** [comment]
Hello! 
When I run "aeroframe -h" the following message appears: 

Traceback (most recent call last):
File "/anaconda3/bin/aeroframe", line 14, in <module>
    from aeroframe.stdfun.run import standard_run
  File "/anaconda3/lib/python3.9/site-packages/aeroframe/stdfun/run.py", line 32, in <module>
    from aeroframe.fileio.settings import Settings
  File "/anaconda3/lib/python3.9/site-packages/aeroframe/fileio/settings.py", line 33, in <module>
    from commonlibs.dicts.schemadicts import get_default_value_dict
ModuleNotFoundError: No module named 'commonlibs.dicts.schemadicts'

When I open pip list I see installed aeroframe ver. 0.1.2
